### ISSUE TITLE
Kirjautuneena "etusivu" tekee paljon virhettä

### ISSUE THREAD

**Issue by jmkahko** [jmkahko/saajuna-frontend#9]
Kirjautuneena "etusivu" tekee paljon virhettä, ennen kuin saadaan data haettua. Virheet lokissa esim. t2m ei löydy

**Comment by jmkahko** [comment]
Etusivulta hävinnyt myös säähavaintoaseman nimi tieto

**Comment by jmkahko** [comment]
Virhe ilmoitus: ERROR TypeError: Cannot read property 'time' of undefined

**Comment by leenakahko** [comment]
Korjattu
